spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/beer_inventory_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: beer_inventory_service_guru
    password: {cipher}f565b94774ad31bbf6c817ea5b1db1595582a00745c40b9f687bafd281a62933
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  artemis:
    user: artemis
    password: {cipher}cb06ee1d8b39b83855b818d671094aa53f2bcf667f1ece939a06170235eb350e