server:
  port: 8083
spring:
  application:
    name: beer-inventory-service
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  # Spring Data hangs when bootstrap-mode was not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: EMBEDDED
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: detect
  # ActiveMQ-Artemis
  artemis:
    user: artemis
    password: simetraehcapa
  zipkin:
    base-url: http://localhost:9411
#logging:
logging:
  level:
    guru:
      sfg: debug
#    org.hibernate:
#      sql: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE
#    com.zaxxer.hikari:
#      HikariConfig: DEBUG