server:
  port: 8888
spring:
  application: 
    name: mssc-brewery-config
  cloud:
    config:
      server:
        git:
          # For Git Repo
          uri: https://github.com/yulikexuan/mssc-config-repo
          searchPaths: '{application}'
          clone-on-start: true
logging:
  level: 
    org.springframework.cloud: debug
    org.springframework.web: debug