server:
  port: 9090
spring:
  application:
    name: sfg-brewery-gateway
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/beer*,/api/v1/beer/*,/api/v1/upcbeer*,/api/v1/upcbeer/*
        - id: beer-order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customers*,/api/v1/customers/**
        - id: beer-inventory-service
          uri: http://localhost:8083
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/api/v1/inventory-failover
          predicates:
            - Path=/api/v1/beer/*/inventory
        - id: beer-inventory-failover
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/inventory-failover*,/api/v1/inventory-failover/**
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: false
logging:
  level:
    guru.sfg.brewery.gateway: DEBUG
    reactor.netty.http.client: DEBUG