spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: beer_service_guru
    password: "{cipher}f565b94774ad31bbf6c817ea5b1db1595582a00745c40b9f687bafd281a62933"
sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8083
    beer-inventory-user-name: inventory
    beer-inventory-password: "{cipher}f565b94774ad31bbf6c817ea5b1db1595582a00745c40b9f687bafd281a62933"