server:
  port: 8082
spring:
  application:
    name: beer-order-service
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: EMBEDDED
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: detect
  # ActiveMQ-Artemis
  artemis:
    user: artemis
    password: simetraehcapa
#logging:
logging:
  level:
    guru:
      sfg: debug
#    org.hibernate:
#      sql: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE
#    com.zaxxer.hikari:
#      HikariConfig: DEBUG
sfg:
  brewery:
    beer-service-host: http://localhost:8081